import React,{createContext,useState} from 'react'

export const Store=createContext();

function DataComp(props) {

    const [data,setData] =useState([
       {
        id: 1,
        Image:  'https://www.bollywood.com/wp-content/uploads/2023/12/kkkgbanner.jpg.webp ',
        heading:  " Karan Johar, Kajol celebrate 22 years of Kabhi Khushi Kabhie Gham",
        category: "Bollywood",
        description: "Mumbai (Maharashtra) [India], December 14 (ANI): Ace filmmaker Karan Johar's family drama film 'Kabhi Khushi Kabhie Gham' turned 22 on Thursday. To mark the occasion, KJo took to Instagram and shared a collage video that featured a few scenes of the iconic film. He captioned the post, “My annual reminder of “It’s all about loving your family”…and my audience who have kept the spirit of #K3G alive even 22 years later. Eternally grateful to magnificent & magnanimous cast – Amit ji, Jaya ji, shahrukh bhai, kajol, duggu and bebo and all other special people in the cast and crew for just making this journey the most memorable one! Thank you today and always.”Helmed by KJo, the film starred Amitabh Bachchan, Jaya Bachchan, Shah Rukh Khan, Kajol, Hrithik Roshan, and Kareena Kapoor Khan in the lead roles.Apart from Karan, Kajol also took to her Instagram account and shared a video that featured a few snaps from the film.She also penned down a long note which stated, “22 years to #k3g ..Another acronym but yes another long lasting memory !!! Yash uncle actually renovated and made new makeup rooms in Filmistan studios permanently just for the shooting of this film because even with the vanity vans it was not going to be enough for this gigantic starrer!”"
        },
       
       {
        id: 2,
        Image:'https://imagesv2.desimartini.com/images/202312/aashiqui-3-1702528276.jpeg?width=1600&quality=50&format=webp?w=1080&q=25' ,
        heading: "Koffee With Karan 8: Aditya Roy Kapur says Kartik Aaryan is 'perfect person' to take forward Aashiqui franchise",
        category: "Bollywood",
        description: "The host Karan Johar asked Aditya Roy Kapur about how he feels not being part of the Aashiqui 3 and replaced by Kartik Aaryan. To which he replied, “I think he’s the perfect person to take the baton forward.In Aditya Roy Kapur’s filmography, his portrayal of Rahul Jayakar in Aashiqui 2 stands out and remains etched in fans’ hearts. The hit franchise is headed for its third installment, replacing him with Kartik Aaryan. In his latest appearance on Koffee With Karan Season 8, Aditya reacted to Kartik stepping into his most-loved character.The host Karan Johar asked Aditya about how he feels not being part of the Aashiqui 3 and replaced by Kartik. To which he replied, “I think he’s the perfect person to take the baton forward.There was no chance I could be in this because, in the second part, my character went for a long swim, from which he is not returning. I think it’s great. I died; where will I come back now? My spirit will come back.” Aditya further joked about returning as spirit in the film. And Karan laughed adding that it would be funny to watch him a ghost haunting Kartik for taking over his popular role.For the unversed, Aashiqui 2 features Aditya alongside Shraddha Kapoor as the leading lady. Directed by Mohit Suri, the 2013 romantic musical drama centers on a turbulent romantic relationship between a failing singer, Rahul Jaykar, and his protege, aspiring Aarohi Keshav Shirke.The film turned out to be a huge hit, grossing Rs 109 crore upon release.Last year, Kartik announced the news of Aashiqui 3 on his Instagram handle. He shared a announcement video with the caption that read, “Ab Tere Bin Ji Lenge Hum Zeher Zindagi Ka Pi Lenge Hum 🎶 #Aashiqui3 ❤️This one is going to be Heart-wrenching !! My First with Basu Da.” Directed by Anurag Basu and backed by Bhushan Kumar under his banner T-seriess"
       },
       {
        id: 3,
        Image: 'https://www.hindustantimes.com/ht-img/img/2023/12/13/550x309/Suniel_shetty_1691565616107_1702478374411.png',
       heading: "Suniel Shetty talks about 'Boycott Bollywood' trend, calls it ‘a bad patch’: Where are all these trolls now?",
       category: "Bollywood",
       description: "Actor Suniel Shetty has spoken about the 'Boycott Bollywood' trend and asked where are the trolls now. Speaking with news agency ANI, Suniel also said it was just a phase that we rode out, adding that the film industry -just went through a bad patch. (Also Read | Suniel Shetty 'never studied beyond bachelor's degree,' shares that education could have helped him) Suniel on Boycott Bollywood trendSpeaking with ANI, Suniel said,'I think it was just a phase, a movement that came and went. Lots of things were happening with Bollywood and '#Boycott Bollywood' was a viral trend, a big movement that was causing further damage to what was already happening in our industry at the time. But when I spoke to Yogi-ji (Yogi Adityanath), I was honest. The first thing that I told him was, 'bhagwan par bhi to ungli uth ti hai, hum to insaan hain (some even point fingers at the Almighty, we are only human). He took it very positively'.Suniel called it a bad phaseWhere are all these trolls now? Does the hashtag exist anymore? Just 10 people here and there, putting out #Boycott Bollywood posts on social media doesn't make any sense anymore. It didn't even make any sense back in the day when it became a viral trend. I believe it was just a phase that we rode out. We just went through a bad patch,-he added."
       },
       {
        id: 4,
        Image:'https://images.indianexpress.com/2023/12/worst-films-of-2023.jpg?w=414' ,
        heading:"Kisi Ka Bhai Kisi Ki Jaan, Ganapath, Adipurush: Some worst Bollywood films of 2023" ,
        category:"Bollywood" ,
        description:"Here are some worst Bollywood films of 2023 which made us wonder why were they even made? While 2023 was a year that saw some Bollywood releases strike a chord with the fans, the same cannot be said for some other movies, These films made us wonder whether they were required or not. Take a look at some of the worst films of 2023 which not only failed to impress the audience but also did not do any magic at the box office Adipurush -This Prabhas, Saif Ali Khan, and Kriti Sanon starrer was an underwhelming take on the Indian epic Ramayan. Fans are still coping with the disastrous VFX. Selfiee- The movie was a remake of the 2019 Malayalam film Driving License. But the Akshay Kumar and Emraan Hashmi film failed to strike a chord with the audience.Kisi Ka Bhai Kisi Ki Jaan-  Even Bhaijaan’s swag failed to revive this poorly made movie by Farhad Samji. Shehzada- This Kartik Aaryan starrer made us wonder what was the need to remake the blockbuster Allu Arjun film Ala Vaikunthapurramuloo.  Dhak Dhak- We saw some better-executed women-led movies than this one which starred Ratna Pathak Shah, Fatima Sana Shaikh, Dia Mirza, and Sanjana Sanghi. Darran Chhoo - This Karan Patel and Ashutosh Rana starrer was a highly forgettable comedy flick.Mission Raniganj-  The Akshay Kumar starrer did not do a riveting subject like the Raniganj coal mine rescue mission justice. " 
       },
       {
        id: 5,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lzDPU.img?w=768&h=432&m=6&x=364&y=40&s=816&d=410',
        heading: " Aishwarya Rai, Abhishek Bachchan, Shah Rukh Khan, Karan Johar, Amitabh dance together at Ambani school event.",
        category: "Bollywood",
        description: " Aishwarya Rai, Abhishek Bachchan, Amitabh Bachchan, Shah Rukh Khan, Karan Johar, Suhana Khan, Agastya Nanda all grooved together to Deewangi Deewangi.At the annual day celebration of Dhirubhai Ambani School in Mumbai on Friday, a host of celebrities were spotted in the audience. Many star kids, including AbRam Khan, Yash Johar and Aaradhya Bachchan, performed at their school's annual function. Now a video of their parents – Shah Rukh Khan, Karan Johar, Aishwarya Rai and Abhishek Bachchan – dancing together at the event has surfaced online.As Deewangi Deewangi from Shah Rukh Khan's 2008 film Om Shanti Om played, all the celebs joined in and danced together in a group off stage. Aishwarya was seen with actor and father-in-law Amitabh Bachchan. Shah Rukh Khan could also be seen dancing to the song with daughter Suhana Khan and Karan Johar. Karan, Shah Rukh and Aishwarya were also seen smiling and talking to each other in the video. Abhishek Bachchan and Agastya Nanda were also seen in videos of the group dance.Kareena, Gauri cheer for Taimur and Ab RamIn other videos from the annual function, Kareena Kapoor was seen cheering for her and Saif Ali Khan's son Taimur Ali Khan as he performed on stage. Gauri Khan was also seen enthusiastically applauding as the kids performed.She sat next to Suhana Khan and Shah Rukh Khan as AbRam performed on stage. AbRam stole the spotlight as he imitated Shah Rukh's signature hands wide open pose during his performance. "
       },
       {
        id: 6,
        Image:'https://www.cine-tales.com/wp-content/uploads/2023/11/Animal-Trailer-Review.jpg' ,
        heading:"Animal box office collection day 15: Ranbir Kapoor film takes India total to ₹484 crore, earns ₹7.5 cr on second Friday" ,
        category: "Bollywood",
        description: "Animal box office collection day 15: Sandeep Reddy Vanga's action film was released in theatres on December 1. As per a report by Sacnilk.com, Animal has earned an estimated ₹484.34 crore nett in India in 15 days. The film stars Ranbir Kapoor, Rashmika Mandana, Bobby Deol, and Anil Kapoor in lead roles. It also features Triptii Dimri, Shakti Kapoor and Prem Chopra.Animal's domestic box office collection Animal, which shows a violent world set against the backdrop of a troubled relationship between Ranbir Kapoor and Anil Kapoor's character, has been doing very well in India amid backlash over promoting misogyny and toxic masculinity. As per the report, Animal collected roughly ₹7.5 crore nett in all languages on its second Friday in theatres. The film had collected ₹139.26 crore nett in its second week and done a business of ₹337.58 crore nett in all languages in its opening week at the domestic box office. More about Animal -Ranbir Kapoor's revenge drama released in theatres worldwide on December 1. Alongside Ranbir, Bobby Deol, Anil Kapoor and Rashmika Mandanna are seen in lead roles in Animal. The film is directed by Sandeep Reddy Vanga of Arjun Reddy and Kabir Singh fame and revolves around a father and son's toxic relationship. While Anil plays the emotionally unavailable father, Ranbir plays the role of the traumatised, angry son."
       },
       {
        id: 7,
        Image: 'https://www.hindustantimes.com/ht-img/img/2023/12/15/550x309/Agastya_Nanda_Sriram_Raghavan_Ekkis_1702637097280_1702637115052.jpg',
        heading:"Agastya Nanda to make big screen debut with Sriram Raghavan’s next film Ekkis; will play an army officer: Report" ,
        category:"Bollywood" ,
        description:"Agastya Nanda is bringing war hero Arun Khetarpal’s life to the big screen with Ekkis. The Sriram Raghavan biopic is set to highlight the father-son bond.Agastya Nanda, who made his acting debut in the Netflix film The Archies earlier this month, is gearing up for his big-screen debut soon. As per a report by Pinkvilla, Agastya will play the leading man in filmmaker Sriram Raghavan’s Ekkis. Produced by Dinesh Vijan, Ekkis is the biopic of 1971 war hero, Arun Khetarpal and will also star Dharmendra in a key role, added the report. Agastya will reportedly start shooting for Ekkis in January 2024.Agastya's big screen debut with Ekkis “2023 was an eventful year for Agastya Nanda as not just did he make his acting debut with The Archies, but also signed on for a Sriram Raghavan film. Agastya has attended several acting workshops with the Sriram and specially trained acting coaches to polish his body language and step into the shoes of India’s most celebrated war hero, Arun Khetarpal,” revealed a source close to the development." 
       },
       {
        id: 8 ,
        Image:'https://www.hindustantimes.com/ht-img/img/2023/12/15/550x309/Deepika_Padukone_prays_Tirupati_temple_1702630251018_1702630268570.jpg' ,
        heading: " Deepika Padukone decks up in cream to offer prayers at Tirupati temple amid tight security; Anisha and parents join her",
        category: "Bollywood",
        description: "Deepika Padukone visited the Tirupati Balaji Temple amid tight security on Friday. The actor could be seen seeking the blessings of Lord Balaji with her father Prakash Padukone, mother Ujjala Padukone and sister Anisha Padukone. Videos of Deepika making her way inside the temple as well as leaving after offering prayers with her family have surfaced online. Deepika was dressed in a cream and golden ethnic look and was seen with a red stole around her as she left the temple premises. Deepika Padukone's Tirupati visit- A day earlier, on Thursday evening, Deepika had arrived in Tirumala with her sister Anisha to seek blessings. She was dressed in black as she visited the temple. Deepika's Tirupati visit comes at a time when she is gearing up for the release of her film Fighter, which also stars Hrithik Roshan and Anil Kapoor in lead roles. Fighter's first song Sher Khul Gaye was unveiled by the cast and makers on Friday." 
       },
       {
        id: 9,
        Image:'https://www.hindustantimes.com/ht-img/img/2023/12/17/550x309/PEOPLE-MATTHEW-PERRY--0_1699086304665_1702789273850.JPG' ,
        heading:"Matthew Perry turned‘angry & mean’ due to excessive ketamine and nicotine lollipops consumption" ,
        category:"Hollywood" ,
        description:"The sudden passing of Matthew Perry sent shockwaves through the entertainment industry, but the autopsy report added a more surprising element, suggesting that Perry's demise resulted from excessive ketamine consumption and other medications in his system. More devastating details about the star's final days were recently revealed in a report obtained by PageSix. The report claims that due to the excessive consumption of some drugs, the FRIENDS star became 'angry and mean'.Matthew Perry relied on nicotine lollipops and testosterone shots in his final days- According to a Page Six report published on Friday, a female acquaintance of the late Matthew Perry revealed that the testosterone shots he had received had caused him to act ‘angry and mean’ in the weeks before his death. Previous reports implied that Matthew Perry's death was linked to a mix of ketamine, coronary artery disease, and buprenorphine effects. However, a recent report claims that Perry had also been consuming Tamoxifen for weight loss, taking an antidiabetic prescription, and using nicotine lollipops, all in conjunction with the lethal combination.  -The toxicology report said that Matthew Perry died while receiving 'ketamine infusion therapy,' but the coroner made it clear that ‘the final infusion’ was not the reason for Perry's demise. Perry was trying to stop smoking in the meantime before he passed away. According to a colleague, Perry made it clear that he would 'never kill himself' and was confident about his future." 
      },
      {
        id: 10,
        Image:'https://www.hindustantimes.com/ht-img/img/2023/12/16/550x309/Screenshot_2023-12-16_213814_1702742905586_1702742914822.png' ,
        heading:"Jessica Chastain recalls ‘sweetest' gift from Taylor Swift: ‘a breakup playlist’" ,
        category: "Hollywood",
        description: "In a recent interview, actress Jessica Chastain shared the ‘sweetest’ gift she has received from Taylor Swift: ‘a breakup playlist.’ In her recent appearance on ‘The Tonight Show Starring Jimmy Fallon’, actress Jessica Chastain revealed the sweetest gift she has received from America's favourite pop star, Taylor Swift.On Friday, December 15, the Scenes from a Marriage actress revealed that Taylor had sent her a break-up playlist after they met each other for the first time at the 2011 Met Gala. “We were both sitting next to each other … and she was so sweet,” said Jessica, 46, to Jimmy, explaining that it was her debut at the annual fashion event.“I just went through a break-up and I was talking to her about that, and we went and danced together — it was such a fun night,” she continued.“And then the next day, I had an email from iTunes that said, like, ‘Taylor Swift’ or whatever, and I just thought that it was a Taylor Swift album,” continued Chastain, before adding that she discovered Taylor, 'had made me a break-up playlist that she sent me! Isn't that the sweetest thing?'“What are you kidding me? That’s unbelievable!” Jimmy, 49, responded. “I know! And here I thought it was like a Taylor Swift advertisement,” added the actress. “And she had, like, curated all these break-up songs to send me to help me get through my break-up.”"
      },
      {
        id:11 ,
        Image:'https://www.hindustantimes.com/ht-img/img/2023/12/16/550x309/garyoldman_1669008141088_1702737224721.jpg' ,
        heading:"Gary Oldman is thankful for Harry Potter and Batman films: 'They saved me'" ,
        category:"Hollywood" ,
        description:"Gary Oldman shared how doing the least amount of work on those films- for the most amount of money, helped him parent his kids after his divorce. Gary Oldman has thanked the Harry Potter franchise and the Batman franchise for saving his life. In his latest appearance at The Drew Barrymore show, Gary expressed his sincere gratitude to both the film franchises he starred in, and said how those films helped him raise his children after his divorce. For the unversed, Gary played Sirius Black in the Harry Potter films, and as James “Jim” Gordon in the Batman films. Talking about his career in retrospect at The Drew Barrymore Show, the Academy Award-winning actor said: “At 42 years old, I woke up divorced and I had custody of [my] boys. That, in itself, was… that was hard because there was a shift in the industry where a lot of productions were being [filmed in] Hungary, Budapest, Prague, Australia, you know, all of these places. So, I turned down a lot of work. Thank God for Harry Potter. I tell you, the two — Batman and Harry Potter— really, they saved me, because it meant that I could do the least amount of work for the most amount of money and then be home with the kids.”" 
      },
      {
        id:12,
        Image: 'https://www.hindustantimes.com/ht-img/img/2023/12/15/550x309/priscilla_1702632421097_1702639748358.jpg',
        heading:"Priscilla review: Sofia Coppola's film slowly and surely ties a bowtie noose around your neck" ,
        category:"Hollywood" ,
        description: "Sofia Coppola's adaptation of Priscilla Presley memoir, on her love story with Elvis Presley is a mood piece between dark and musical.In an exclusive interview with this writer, Sofia Coppola said her movie on Priscilla Presley is designed as a ‘doll stuck in a doghouse.’ Priscilla consistently feels like that – the girlhood of a teenager restricted by the palatial mansion of a grown-up man at the peak of his career. But the dog seldom bites or barks, it only growls as soon as the doll takes a spring in her step, forcing her to recede to the shadows. Fairy tale gone wrong Sofia retains what Priscilla reiterates in her 1985 memoir Elvis and Me, that there was deep love between her and Elvis Presley. She meets him through a common acquaintance when she's 14 and he's 24. To her, Elvis symbolises the rebellion and freedom that's been kept away from her in the contained army upbringing. Like her parents, we fear her getting smitten by Elvis, but Sofia makes sure the story marches on with the combined force of fate and a young girl's agency. Priscilla is not taken in by Elvis' music or his larger-than-life personality. In fact, she's in love with his small gestures and giant sweeps in love, including him asking her parents to move her to his mansion at Graceland. With cinematographer Philippe Le Sourd's scrutinising lens and editor Sarah Flack's carefully crafted beats, Sofia builds what could be a fairy tale gone wrong. She fills the room with darkness in daylight."
      },
     {
        id: 13,
        Image:'https://th.bing.com/th/id/OIF.LQnbBc2at5C82GsFrAH8eg?w=317&h=180&c=7&r=0&o=5&pid=1.7' ,
        heading:"New romance or collaboration? Drake and Camila Cabello spotted together" ,
        category:"Hollywood" ,
        description:"The duo was photographed enjoying the sun in Turks and Caicos, with Drake donning a breezy beach shirt and Camila stunning in a short black dress.Drake and Camila Cabello have set tongues wagging as they were recently spotted together on a getaway, sparking rumors of a potential romance or musical collaboration. The duo was photographed enjoying the sun in Turks and Caicos, with Drake donning a breezy beach shirt and Camila stunning in a short black dress.This rendezvous comes eight months after Drake started following Camila on Instagram, leading fans to speculate about their connection. Reports suggest that producers from Drake's team also began following the 'Crying in the Club' artist. The recent in-person meet-up has ignited a flurry of excitement on social media, with fans speculating on the nature of their relationship. While some enthusiasts anticipate a budding romance between the two megastars, others are hopeful for a potential collaboration that could reshape the music landscape. The viral pictures and videos from their tropical retreat show them engaged in animated conversations and enjoying activities like a speedboat ride and jet skiing." 
      },
       {
        id:14 ,
        Image: 'https://www.hollywoodreporter.com/wp-content/uploads/2023/12/Fantasia-Barrino-Getty-H-2023.jpg?w=1000&h=563&crop=1&resize=681%2C383',
        heading:" 'The Color Purple' Star Fantasia Barrino Says She and Family Were Racially Profiled by Airbnb: “I Dare Not Stay Quiet”" ,
        category: "Hollywood",
        description: "Fantasia Barrino shared that she and her family were racially profiled by Airbnb when they stayed at a house booked on the website for her son's birthday.The Color Purple star posted on her official social media accounts, explaining that she rented a house for her son and his friends and invited people over to celebrate during the day. Once the festivities ended, the number of guests staying the night matched the number on the reservation, so they did not break any rules.  “My stomach is so uneasy this morning,” she wrote on Twitter. “I don't say much when people do me wrong, but I can't stay quiet on how my family and I were just treated from a host with @Airbnb @airbnbhelp trying to kick my kids and I out at 12:00 midnight. The host accused us of having a party with loud noises outdoors because they saw balloons being dropped off and a game truck with no generator in the early part of the day.”  The actress pointed out that the website never said she couldn't have people over the house and noted that the sayings on the wall, outdoor fire pit and jacuzzi, game room and balloon ribbons left in the garage showed that people often had gatherings there.“It's evident to me this was racial profiling and the treatment we received was due to the color of our skin,” she added. “I wanted my son to enjoy his friends (10-12) year old and make him feel special as I have been traveling for the last 35+ days promoting a movie I starred in. This time, I dare not stay quiet.”Airbnb's help account replied to her post, noting that the company does not condone discrimination in any way and shared a link to its nondiscrimination policy. It also asked her to send a direct message with the email address connected to the booking, so the team could follow up with her."
      },
      {
        id:15 ,
        Image: 'https://www.hollywoodreporter.com/wp-content/uploads/2023/12/GettyImages-1854395647-H-2023.jpg?w=1296&h=730&crop=1&resize=681%2C383',
        heading:"Cher on Rock and Roll Hall of Fame Snubbing Her: 'They Can Just Go You-Know-What Themselves' " ,
        category: "Hollywood",
        description: "Cher called out the Rock & Roll Hall of Fame for failing to induct her throughout her record-breaking decades-long music career. The Grammy-winning singer, who made history this month as the first female artist to have a No. 1 song in each of the past seven decades, shared her thoughts on Friday’s episode of The Kelly Clarkson Show regarding her exclusion from the prestigious music museum.“You know what, I wouldn’t be in it now if they gave me a million dollars,” Cher told host Kelly Clarkson, who was clearly surprised, adding, “Are you serious? … That is brand new information for me.” “I’m not kidding you. I was about to say something else. … I was about to say I’m not shitting you,” the legendary singer added. “I’m never going to change my mind. They can just go you-know-what themselves.”Cher’s comments came after Clarkson praised her latest milestone, where she became one of two artists, including The Rolling Stones, to have a song reach the top of the charts for the past seven decades straight, thanks to her latest Christmas track, “DJ Play A Christmas Song.”The singer also joked of the accomplishment, “It took four of them to be one of me.”Looking past the Rock & Roll Hall of Fame snub, Cher acknowledged that she “changed music forever with ‘Believe.’” The single, which was released in 1998, spent four weeks at No. 1 on the Billboard Hot 100 chart and continues to be a success to this day.Clarkson added that she hears some similarities between “Believe” and the singer’s latest holiday single, “DJ Play A Christmas Song.” “I feel like how massive in pop culture and everything and how it hit and impacted the pop culture community — ‘Believe’ did, I feel like that’s the same vibe as ‘DJ Play A Christmas Song,’” Clarkson said. “It’s that same vibe. No one has that sound. I almost think, if somebody sent me that song for my Christmas record, I was like, ‘I don’t know if I could pull this off. I don’t know if this is me.’ Like it’s so you, the sound is so Cher. It’s so incredible. I love it so much, and I kind of feel like it’s the same thing, the same impact.”"
      },
      {
        id:16 ,
        Image:'https://www.hollywoodreporter.com/wp-content/uploads/2023/12/Ryan-Reynolds-Channing-Tatum-Aaron-Adam-Nee-Split-NEW-Getty-H-2023.jpg?w=1296&h=730&crop=1&resize=681%2C383',
        heading:"Warner Bros. Wins Bidding War for Ryan Reynolds-Channing Tatum Package ‘Calamity Heist’ " ,
        category: "Hollywood",
        description: " 'The Lost City' filmmakers Aaron and Adam Nee are behind the feature on which the bidding put the above-the-line costs over $50 million, according to sources.The studio is in final negotiations to win the high-priced bidding war for Calamity Hustle, the action comedy that has Ryan Reynolds and Channing Tatum attached to star as wayward bothers.Aaron and Adam Nee, the sibling team that was behind the 2022 sleeper hit The Lost City, wrote the script and are attached to direct.Reynolds and Tatum are also producing via their respective banners, Maximum Effort and Free Association. Also producing is Kevin Walsh, who is currently in the awards season mix with Napoleon, as are the Nees via their banner Persons Attempting.The package hit Hollywood after Thanksgiving and attracted only a select group of buyers — legacy studio Warners, and streaming goliaths Amazon and Netflix. The small pool of bidders was a result of the high-priced nature of the package. The actors were asking for a minimum of $20 million apiece, while the Nees were seeing paydays in the $6 million to $8 million range. With potential costs of $50 million or more out of the gate, the project was out of reach for most movie companies.According to sources, one offer came in at $175 million for the package, including above-the-line costs. The logline, according to sources, concerns a down-on-his-luck former Los Angeles detective turned private investigator who, after being shaken down by a vicious crime lord, must track down his estranged brother, who is responsible for interfering with a diamond heist.The project is not a go movie, however, as sources say the script needs a lot of work that one actor in particular may help oversee."
      },
      {
        id:17 ,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lnuaD.img?w=768&h=432&m=6',
        heading:"Expert Speaks On Whether It Is Safe To Eat Refrigerated Food " ,
        category: "Food",
        description: " There’s a lot of information on whether one should eat refrigerated food or not. While there are a lot of claims which say that you shouldn’t eat refrigerated food. However, throwing away excess food isn’t a great option and eventually, you’ll have to refrigerate them to prevent them from getting spoilt. So, what should you do? Read on as Dr. Saurabh Sethi, a Gastroenterologist sheds light on whether it is safe to eat refrigerated food.In a video shared on Instagram, Dr. Saurabh Sethi says, “There are three myths about refrigerated food I will bust today.” He then goes on to speak about the myths and also shares facts. Dr. Sethi says, “Myth 1, leftover food equals food poisoning. This is not true. When stored and handled properly, most leftovers are safe to eat. Within two hours of cooking, store leftovers in airtight containers in the fridge.”Speaking of Myth 2, Dr. Sethi says, “Leftovers are forever. That is absolutely not true either. Leftovers have a shelf life. The general rule of thumb is to consume those within three to four days. After that, the risk of spoilage and foodborne illnesses increases.” While you can keep your leftovers in the fridge, make sure to eat them within a span of a few days. Don’t keep the food in the refrigerator for a long time and consuming it after so long might lead to food poisoning and other illnesses. About Myth 3, Dr. Sethi says, “Reheating fixes everything. Not true! Reheating leftovers can kill some bacteria but it will not remove toxins produced by certain microbes. Make sure to consume your refrigerated food within 3 to 4 days.” While these facts are true, there are certain foods that you shouldn’t reheat because reheating increases certain compounds present in them which can eventually turn out to be toxic for the human body. Read on to know foods that you should avoid reheating. Spinach and celery, rich in nitrates, may convert to cancer-causing nitrosamines. Potatoes and rice may have bacteria leading to food poisoning. Seafood and fish are prone to spoilage, resulting in changes like dryness or odour. Fried foods like steak and eggs might change in texture, flavour and loss of nutrition when reheated.  Disclaimer: Tips and suggestions mentioned in the article are for general information purposes only and should not be construed as professional medical advice. Always consult your doctor or a dietician before starting any fitness programme or making any changes to your diet."
      },
      {
        id:18 ,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1l67aO.img?w=768&h=432&m=6',
        heading:"Hypertension diet: Tips to control high BP and 5 foods that are a must-have " ,
        category: "Food",
        description: "Increased work pressure and changes in eating habits have a direct impact on people's health. The rapidly changing lifestyle brings with it lots of challenges, and this is the reason why there is a rise in diabetes, BP, and heart-related diseases around the world. For individuals grappling with hypertension, a mindful approach to nutrition is the need of the hour. Though medical experts suggest taking medicine for hypertension, diet can bring in a lot of changes in this condition. Here is a list of foods along with a few dietary changes that are known to help in controlling hypertension. Take a look… Adopt a plant-based diet  -Fruits, vegetables, whole grains, and legumes are rich in potassium, a mineral known for its blood pressure-lowering effects. These foods also contribute essential vitamins, minerals, and fibre, promoting overall heart health.Limit sodium intake  Sodium can elevate blood pressure. Opt for fresh, unprocessed foods, and minimise the use of table salt. Be cautious with packaged and restaurant foods, often high in hidden sodium.  ALSO READ: These low-sodium foods can reduce Blood Pressure levels naturally.  Choose lean proteins Opt for lean protein sources like poultry, fish, legumes, and tofu while limiting red meat. Fish rich in omega-3 fatty acids, such as salmon, can be particularly beneficial. Healthy fats matter Incorporate heart-healthy fats like olive oil, avocados, and nuts. These fats contribute to overall cardiovascular well-being. Moderate alcohol consumptionIf you choose to consume alcohol, do so in moderation. For women, this means up to one drink per day, and for men, up to two drinks per day. Limit added sugars Excessive sugar intake can contribute to weight gain and other cardiovascular risks. Choose natural sweeteners like honey or opt for desserts in moderation.Here is a list of foods that can become a part of everyday diet for controlling hypertension…  Strawberries  If you want to lower your blood pressure, berries are a great option. Rich in antioxidants and flavonoids, strawberries can improve blood flow and reduce the risk of high blood pressure. Leafy greens. Green leafy vegetables are very beneficial for our health. This is why doctors recommend making it a part of your diet. These leafy vegetables are rich in potassium and nitrate, which help in relaxing blood pressure and help in reducing your blood pressure. "
      },
      {
        id:19 ,
        Image: 'https://i.guim.co.uk/img/media/534c3b8a904faf364892763f1196dcf278edd0f4/0_59_1400_840/master/1400.jpg?width=620&dpr=1&s=none',
        heading:" What dish will crown your Christmas table? Forget tradition – mine’s a samosa tree" ,
        category: "Food",
        description: "Since Nigella Lawson called out Christmas cake as a festive food that should be forgotten (an opinion with which I wholeheartedly agree), I’ve been thinking about re-evaluating our Christmas food choices. It’s time to accept that letting go of the festive traditions that no longer suit our appetites or our lifestyles is perfectly OK. Scaling back on the foods we don’t love means we can make room for the ones we do. If that means cooking a small air fryer roast this year, then great – at least you won’t be lumbered with unwanted leftovers for a week after Christmas. My Instagram and TikTok feeds are offering me a smörgåsbord of Christmas meal ideas – some ridiculously indulgent and made entirely of flavoured butter; others more practical, such as big platters of all the sides with no main dish, an all-day breakfast, “picky bits” or buffet-style eating you can graze on all day. I now dream of potato grazing boards: wedges, chips, curly fries, waffle cuts, potato skins and crisps galore, tag-teamed with a dip-stravaganza.I can’t help but note that this communal style of eating is typical of many Asian dining norms, including those of my own Indian culture. Celebrations centre around food, and eating an array of dishes all at once. It’s a casual and sociable way of feasting that carries with it a sense of liberation and pleasure in helping yourself to more of what you love. At Christmas, my family goes for food that’s easy to prepare in bulk, since we’re a party of 40: Indo-east African channa bateta (a mix of potatoes and chickpeas cooked in coconut milk and topped with cassava crisps, chillies and raw mango chutney), or perhaps a selection of chaats, or dosa with different fillings (everything from classic potato to pizza or noodles), traybakes of multiple fajita fillings, meze and – my favourite of all – one huge biryani and a riot of different raitas.For now, I’ve banished the Modha Christmas aubergine and introduced a new family tradition: an ugly delicious Christmas tree made entirely of samosas, complete with an aloo tikki star at the top. Any leftovers will go in the freezer for when the next craving hits, sometime in the new year. Then we’ll have eaten it two years in a row – which seems like the start of a new tradition. "
      },
      {
        id:20 ,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lsXd8.img?w=550&h=309&m=6',
        heading:" Taste of Life: Bonding over food during Christmas" ,
        category: "Food",
        description: "Enthusiastically promoted by authors like Charles Dickens and Washington Irving in the nineteenth century, Christmas celebrations were revived by the longing on the part of the Victorian middle class for an idealized past comprising familial sentiments and charitable thoughts towards those who were less fortunate.Food had always been an integral part of Christmas festivities. Certain dishes became associated with Christmas, sometimes because they had a symbolic meaning, and sometimes because they were too expensive to be eaten all the time. Pork was a favourite Christmas dish in Russia and Europe from Greece to Germany in the nineteenth century. It was one of the most favoured dishes in England too. The boar was sacrificed to the sun at Christmas as late as the early nineteenth century: a boar’s head formed part of a continuing ceremony since at least the fourteenth century held at The Queen’s College, Oxford. Pigs were an important source of meat from the Saxon period and remained so in the medieval period, probably representing the second most important source of meat after cattle. Pork, mutton, and beef were important foods not just because of their nutritional significance, but also because they could be smoked and salted, which preserved the produce for longer. Other parts of the animal were also used, stored or rendered for fats such as cheese and butter. Suckling pigs provided a tasty meal, but wild boar was appreciated as it was richer in flavour than domestic pork. Brawn was served with vinegar or syrup of wine and honey.British troops in Poona appreciated having pork for their Christmas dinner. That sold to the army was usually purchased at the canteens in barracks, for as a rule pork was never on sale in most of the native bazaars. Christmas was one occasion where the officers could hunt a wild boar.In the short story “Jack Vereker’s Ghost” written by Sir Randal H Roberts in the late nineteenth century, the protagonist Albert Forrester, stationed at “Ghoorpoorie lines”, Poona, during Christmas, is lounging in the verandah of the mess room, thinking of the jolly Christmas times he had spent at home – the pheasant shooting, the hunting, the three woodcock he shot in the laurels the day before Christmas one year, the family dinner-party, the servants’ ball, and the decoration of the church. He and his friends then decide to spend Christmas day hunting the wild boar near Poona."
      },
      {
        id:21 ,
        Image: 'https://c.ndtvimg.com/2023-12/t1u31398_tricolour-food_625x300_09_December_23.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350',
        heading:"  Moments Of Pride For Indian Cuisine And Indian Chefs In 2023" ,
        category: "Food",
        description: "It has been a year of fantastic growth and evolution for Indian cuisine. Indian ingredients and culinary practices have received recognition on the world stage in different ways. Indian chefs, restaurants and homegrown companies have won incredible accolades, shining the global spotlight on the richness and diversity of our regional cuisines. As the year draws to a close, we have rounded up 10 key moments of pride for Indians in 2023. We have included several pieces of good news that made headlines worldwide throughout the year. Check out the full list below.Here Are 10 Culinary Achievements That Made India Proud In 2023:1. World's 50 Best Restaurants 2023 Included Two Centred Around Indian CuisineTwo restaurants serving Indian cuisine were named among the World's 50 Best Restaurants for 2023. Helmed by Chef Himanshu Saini, Tresind Studio, Dubai was ranked 11th. It is the only Indian two Michelin-starred restaurant in the United Arab Emirates (UAE). Gaggan Anand, Bangkok was ranked 17th. The prestigious establishment, named after its owner and executive chef, has also been proclaimed the Best Restaurant in Asia several times in the past.2. Three Indian Restaurants Made It To Asia's 50 Best List for 2023Wondering which restaurants located in the country won accolades this year? Among Asia's Top 50 were Masque, Mumbai (16th place), Indian Accent, Delhi (19th place) and Avartana, ITC Grand Chola, Chennai (30th place). Before this, for seven consecutive years from 2015 to 2021, Indian Accent in Delhi had been named India's best restaurant in India by the same organisation.3. Four Indian Bars Were Featured On Asia's 50 Best ListIt was not only restaurants that won the global spotlight this year. A number of bars in the country were also recognised among Asia's top 50. Sidecar in New Delhi was ranked 18th, The Bombay Canteen (Mumbai) was placed 35th and Copitas (Bengaluru) was ranked 38th. Masque in Mumbai received yet another accolade when its newly launched bar "
      },
      {
        id:22 ,
        Image: 'https://c.ndtvimg.com/2023-12/bde9ep28_puli_625x300_17_December_23.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350',
        heading:"How To Bake Puli: Ladakh's Famous Atta Cookie Recipe " ,
        category: "Food",
        description: " Puli or Tagi Puli is a popular cookie recipe from Ladakh. 'Tagi' is a generic term used for puris and rotis; and 'puli' means small pieces. Locals in Ladakh prepare these cookies at home in the morning and enjoy them with jam or butter, paired with a cup of hot tea or coffee. 'Since this form of bread can also be enjoyed cold, people often carry it when they are travelling and later eat it with tea or even add some spices to it,' Danish Din, a hotelier, shares with NDTV Food. 'You can eat it warm or cold, depending on your choice. If you keep this bread in a hot case or wrapped in a cloth, it can be eaten for over two to three days and will not develop any foul smell or get bad in that time.'Tagi Puli is shaped like a Chocolate Cookie. If you do not have a friend from Ladakh or have never been to the place, it could be tricky to find this snack elsewhere. Curious foodies can attempt to make this cookie at home. Here is the recipe:Ingredients You Need To Bake Tagi Puli1 Tbsp Baking powder1 Tbsp Oil3/4 Cup Pure cow milk1 Cup Wheat flour1/2 Cup White or brown sugar1/4 Cup Egg wash or yoghurtHow To Bake Tagi Puli  | Tagi Puli Step-By-Step RecipeHere is how to bake and enjoy Tagi Puli from the comfort of your home:Add baking powder and oil to the wheat flour in a wide container. Mix sugar in the milk and then slowly pour the milk into the flour mix while kneading to form a dough. Let the dough rest for 20 minutes.Once the dough is ready, take out small portions and roll them into a ball. Now slightly press them to achieve the desired round shape. Alternatively, you can roll out the dough and then use a cookie cutter.Using a knife, mark horizontal and vertical lines on the cookie dough to achieve the look of this cookie. You can also use a cookie stamp to add a design on top.Brush some egg wash on the top of the cookies. For vegetarians, you can also use yoghurt.Arrange these cookies on a baking tray and pop them in a preheated oven at 130 degrees for 30 minutes.Once baked, serve with a cup of tea or coffee."
      },
      {
        id:23 ,
        Image: 'https://c.ndtvimg.com/2023-12/1ksqup98_burger-idli_625x300_14_December_23.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350',
        heading:" 'Dunki Idli Burger' Leaves Fans Wondering About SRK's Connection To It" ,
        category: "Food",
        description: "Street food in India is an adventure for every food lover, offering a delicious paradise on the go! Street food vendors take it up a notch by experimenting with diverse food items, and transforming familiar dishes into exciting novelties. Take the 'dosa sandwich,' for example. Adding to the excitement, we are eagerly awaiting the release of SRK's latest movie, 'Dunki,' and the buzz is contagious. Meanwhile, a recent culinary discovery by a food vlogger in Mumbai has added to the culinary charm - a street stall serving a delightful twist with the 'Dunki burger idli.'Taking innovation further, the vendor takes idli, slices it in half to form “burger buns”, and substitutes traditional ketchup with a medley of South Indian chutneys, including some coconut and green chutney. Grating cheese over the idli buns, he layers the previously prepared mashed potato mixture as the patty, finishing it off with a dollop of mayonnaise. To enhance the visual appeal, he grates carrots over the creation, folds the idli buns on top of each other, and voila – the idli burger is ready to be served, accompanied by sides of sambhar. "
      },
      {
        id:24 ,
        Image: 'https://th-i.thgim.com/public/migration_catalog/article10113952.ece/alternates/LANDSCAPE_1200/15DMC_WRAP_RECIPE',
        heading:"Try the simple split green gram wrap with this recipe " ,
        category: "Food",
        description: "This lentil wrap is the perfect canvas for when you want to grab a quick dinner. Made with split green lentils it is protein rich and filling. Ingredients  : One cup split green lentils ,One green chilli ,One teaspoon salt ,One teaspoon olive oil, ENO fruit salt or baking soda (a pinch), Three fourth cup of mineral water (for soaking the lentil) ,Preparation - 1.Wash lentil with tap water and use your hands to rub it, discard its water three to four times . 2.Now use mineral water for soaking it. 3.Soak it for almost two to three hours 4.Later, add green chilli and salt in soaked lentil 5.Take a clean and dry blender, pour the soaked lentil in it and blend it for a minute. The batter need not be too runny nor thick. 6.Pour out the batter in a dish and keep aside. 7.Grease a non stick medium sized pan and turn to medium flame.8.Meanwhile add a pinch of baking soda in the lentil batter. Some people even add a pinch of Eno. Beat well with a hand beater and start spreading it on a hot greased pan.9.Once the wrap starts getting separated from sides, it is ready to be flipped.10.Cook for another minute and turn off the flame. 11.You can fill it with raw veggies/cooked okra or grill chicken. "
      },
      {
        id:25 ,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lFonA.img?w=549&h=309&m=6',
        heading:"Year Ender 2023: From biohacking to metaverse wellness, 8 top health and fitness trends that went viral this year " ,
        category: "Fitness",
        description: "As we bid farewell to 2023, it's intriguing to reflect on the dynamic shifts and innovations that have taken the health and fitness world by storm. From cutting-edge technologies to holistic lifestyle approaches, the year has witnessed a myriad of trends that have captured both attention and enthusiasm. The top health and fitness trends of this year reflect a harmonious blend of functional exercises, ancient wellness practices, and a collective desire for personalised, sustainable lifestyles. It's time to look back at the practices that have reshaped the way we approach our physical and mental well-being. Scroll down to check out the most popular trends that have not only sparked conversations but have also paved the way for a healthier and more vibrant future. 1. Gamified fitnessThe integration of gaming and fitness is evolving. Leading companies in the field are now offering cardiovascular exercise equipment that enhances the interactive gaming experience. Gamified fitness uses aspects of video games such as leaderboards, medals, points and awards to encourage and engage users. Fitness trackers are just one of the many gamified fitness applications and programmes available. They allow users to compete with friends and family and receive incentives for achieving goals. 2. Mini workouts Many people prefer to break up their exercise into shorter, more frequent sessions rather than devoting an hour to it. This could be split into three 15-minute sessions throughout the day, or short bursts of five to ten minutes. Many people find these shorter sessions easier to fit into their daily schedules, while others prefer to focus on one part of the body and take a few hours off before working that part again, rather than doing both at the same time and wearing out the second muscle group. 3. Biohacking The DIY biology technique known as 'biohacking', which aims to improve wellbeing, performance and health through deliberate intervention, has been popular in 2023. For example, nutrigenomics, a type of biohacking, focuses on the interactions between your unique genes and the food you eat. Through this type of biohacking, individuals seek to identify and maximise the ways in which different nutrients influence their thoughts, emotions and actions. 4. Functional fitness 5. Wellness coaching "
      },
      {
        id: 26,
        Image: 'https://th.bing.com/th/id/OIP.9M8CA4N94hvrQbN0FlChYwHaE8?w=297&h=198&c=7&r=0&o=5&pid=1.7',
        heading:"Five realistic strategies to adopt during your weight loss journey " ,
        category: "Fitness",
        description: "Start by setting simple and achievable goals for yourself In today’s fast-paced world, where the demands of modern life take precedence over physical and mental health needs, it is crucial to emphasise the significance of prioritising a healthy lifestyle. However, the journey towards a healthier life poses a challenge for millions of individuals worldwide, largely due to concerns related to weight and obesity. The issue of obesity is undoubtedly multifaceted, with genetic and lifestyle factors contributing to its complexity. A few ways which can help you to stay fit and lose weight are as below:Creating sustainable habits is the foundation for long-term success in weight management. Instead of chasing quick fixes, it is important that you prioritise health-conscious routines. Begin by adopting a balanced diet, incorporating regular physical activity, and mastering stress management. Keep in mind, that consistency is the secret to maintaining a healthy weight. Gradual lifestyle changes pave the way for lasting results. Incorporating a healthy diet is crucial for managing weight effectively. Incorporating a well-balanced diet while avoiding processed foods and sugary drinks is vital for weight maintenance. Essential minerals such as Zinc and Iron are crucial for antibody production and a strong immune system. For those struggling to maintain a nutritious diet due to a busy lifestyle, convenient on-the-go supplements such as Vestige Veslim Shake can be a practical solution. Prioritising adequate sleep is another crucial aspect of a successful weight-loss journey. Quality sleep plays a significant role in regulating hormones that control appetite and metabolism. Aim for 7-9 hours of restful sleep each night to support your weight management efforts. Poor sleep can lead to increased cravings for unhealthy foods and hinder your ability to make healthy choices during the day. Keeping a journal can be a powerful tool for tracking progress and staying accountable. One can use a variety of health monitoring apps to track daily food intake, exercise habits, and physical and mental wellness. This can help identify patterns, triggers for overeating, and areas where adjustments are needed. Parallelly, it also serves as a source of motivation when you can see the positive changes you've made over time."
      },
      {
        id:27 ,
        Image: 'https://th.bing.com/th/id/R.8174426628c86b23d1c666ef99f5a693?rik=y%2bipCwaIz8VKXA&riu=http%3a%2f%2fwww.pixelstalk.net%2fwp-content%2fuploads%2f2016%2f06%2fFree-Desktop-Fitness-Wallpapers-Images.jpg&ehk=8vU6dAJTzv84UHR%2bCWvqvBY1MnntTtbvIc40SIoBBXM%3d&risl=&pid=ImgRaw&r=0',
        heading:" Employees Lace Up As Chinese Company Ties Bonuses To Fitness" ,
        category: "Fitness",
        description: "Employees in various industries are accustomed to receiving bonuses based on their performance, with each company having its policies governing such rewards. However, recent changes to bonus policies have left employees at a Chinese company, The Dongpo Paper, in shock. According to a report from the South China Morning Post, The Dongpo Paper has shifted its performance bonus criteria from work habits to fitness, a move that has prompted employees to focus more on their physical well-being to secure bonuses. Situated in Guangdong Province, China, The Dongpo Paper Company recently implemented a notable alteration to its traditional performance bonus policy. Instead of assessing performance, the bonus is now determined by the fitness levels of employees. According to reports, employees will receive a full monthly bonus only if they run 50 kilometres within a month. Additional bonuses include a 60 per cent reward for running 40 kilometres, a 30 per cent bonus for a 30-kilometre run, and an extra 30 per cent for those achieving a 100-kilometre run in a month. Notably, the new policy extends beyond running, incorporating activities such as speed walking and mountain hiking. These activities can contribute 30 or 60 per cent of the total exercise tally and will be tracked through a dedicated app on employees’ phones. As news of this policy went viral on social media, the company’s leadership clarified that the intention behind the change was to promote employee health. Employees have expressed contentment with the new approach, emphasising that it not only encourages fitness but also provides a financial incentive. In a separate development ahead of Diwali, the Indian government’s Finance Ministry made a significant decision regarding non-productivity-linked bonuses for central government employees in the fiscal year 2022–23. The Finance Ministry set the ceiling for computing a non-productivity-linked bonus (ad hoc bonus) at Rs 7,000. An office memorandum from the Department of Expenditure under the Finance Ministry stated that the non-productivity-linked bonus (ad hoc bonus) equivalent to 30 days of emoluments for the accounting year 2022–23 has been granted to central government employees in Group C. The bonus is also applicable to all non-gazetted employees in Group B who were not covered by any productivity-linked bonus scheme."
      },
      {
        id:28 ,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lCUnE.img?w=549&h=309&m=6',
        heading:"New Year 2024: Tips for achieving your fitness resolutions " ,
        category: "Fitness",
        description: "As 2023 draws to a close, individuals are gearing up to formulate their New Year's resolutions. While many focus on fitness goals, a significant number struggle to maintain them beyond the first few months of the new year. However, when it comes to prioritizing health and fitness, there is no specific, Choose Realistic Fitness Resolutions: Individuals frequently set unrealistic fitness goals, which can be challenging to achieve. This may lead to demotivation and a reluctance to engage in regular workouts. Therefore, it is crucial to opt for an attainable goal that can be reached within a few months to maintain motivation and foster a positive fitness journey. Don't Wait Till the New Year: You don't need to wait until the end of the year to embark on a fitness journey. Start warming up and initiate your fitness routine before the year comes to a close. Find A Fitness Buddy: Exercising with a friend not only adds an element of fun but also serves as a source of motivation. Working out together allows for mutual support and encouragement, helping both individuals stay motivated and committed to their fitness journey. Plan in Advance: Establish your fitness goals between Christmas and New Year, rather than waiting until New Year's Eve. Use this time to plan by scheduling an appointment with a personal trainer or initiating a gym membership. Have a Plan B: Always have a backup plan in case of interruptions that prevent you from going to the gym or taking a walk. Explore home exercises to ensure you can stay active even in challenging situations. Add Some Variety to Your Workouts: Frequently changing your exercise routine can enhance enjoyment, maintain motivation, and significantly increase the likelihood of sticking to your fitness regimen. "
      },
      {
        id:29 ,
        Image: 'https://images.indianexpress.com/2023/12/kunal-kemmu_1600_insta.jpg?w=640',
        heading:"Kunal Kemmu’s intense session in the gym takes fitness up a notch  " ,
        category: "Fitness",
        description: "Social media went into a frenzy as actor Kunal Kemmu flaunted his strength in the gym with his intense fitness moves. The Golmaal actor wrote in the video’s caption, “Work it!”. The message resonated with many of his followers who were left in awe of his incredible strength as he demonstrated moves like air walking, weighted squats, and a heavy leg press, among others.Chef Maria Goretti wrote, “Oh my god Kunal, this is crazy amazing…”, while Sandhya Mridul shared, “Whaaaaat”, as Saiyami Kher mentioned, “Woah”.While blind following is not recommended, here’s a guide to mastering weights with proper form and technique.It’s essential to include a variety of exercises to target different muscle angles and movement patterns for comprehensive leg muscle development. “Additionally, proper form and gradual progression in weight are crucial to maximising benefits while minimising the risk of injury,” said Goyal.1. Start Light – Begin with lighter weights to master proper form and reduce the risk of injury. Focus on technique before increasing the load. 2. Learn Basic Movements – Master fundamental exercises like squats, deadlifts, bench presses, and overhead presses. These compound movements engage multiple muscle groups for efficient workouts. 3. Prioritise Form – Maintain proper posture, with attention to spine alignment and joint positioning. Good form is crucial for both effectiveness and injury prevention. 4. Controlled Movements – Perform exercises with controlled, deliberate motions. Avoid rapid or jerky movements to engage muscles effectively and reduce the risk of strains. 5. Breathing Technique – Coordinate your breathing with movements. For example, deep breaths before descending in a squat and exhaling during the exertion phase. This stabilizes the core and enhances performance. 6. Seek Professional Guidance – Consider consulting a fitness professional or certified trainer for personalised advice. They can help correct form, provide tailored workouts, and ensure a safe and effective training program."
      },
      {
        id:30 ,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lmIwt.img?w=768&h=367&m=6&x=206&y=46&s=711&d=84',
        heading:"Fitting into the fitness regime " ,
        category: "Fitness",
        description: "Participants from Tamil Nadu, Kerala, Karnataka, Telangana, Andhra Pradesh and Puducherry, both men and women, came together to showcase their talents in Chennai. CHENNAI: It was the “it moment” for most of the bodybuilders. A day that they had been looking forward to for a long time. When discipline and determination takes priority, for success, all you have to do is wait patiently. This was the message re-iterated by the enthusiastic participants at the Mr and Ms South India 2023 zonal bodybuilding and fitness championship presented by the World Fitness Federation (WFF) TamilNadu conducted on Sunday at Decathlon, Nolambur. Over the course of the last two decades, the competition organised by the WFF and World Fitness Association (WFA) has seen active participation. This year 300 enthusiastic participants from 21 diverse categories registered in the competition, comments Mohan Kumar, president of World Federation Association, Tamil Nadu. Participants from Tamil Nadu, Kerala, Karnataka, Telangana, Andhra Pradesh and Puducherry, both men and women, came together to showcase their talents in Chennai. Mohan said, “Despite the challenges brought by the recent cyclone in the city, organising and executing significant large-scale competitions like this demanded a lot since participants arrived from all parts of south India. However, the notion of cancelling or postponing was never considered.” Mohan who was Mr South India in 2018 added that the participants’ unwavering dedication and five to six months of training, should be appreciated. “The commitment was to ensure that their efforts would not be in vain,” he said. He also emphasised the importance of fitness in our daily lives. He said, “Bodybuilding helps to keep the body healthy, teaches discipline and also doesn’t promote unhealthy habits like smoking or drinking which could harm your potential and physique.” The event was the 9th competition organised by the Federation this year, and collaborated with One Tan and Viva Fitness. The New Indian Express was the media partner.  The WFF is a global bodybuilding organisation,with its headquarters situated in Australia. With a presence in India for over 15 years, it has been promoting bodybuilders and a healthy lifestyle. With regular competitions, they hope to promote the message of staying healthy with consistent effort.  "
      },
      {
        id: 31,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1l7oRI.img?w=768&h=432&m=6',
        heading:"Start a 21-day lifestyle routine to kickstart your fitness in the new year " ,
        category: "Fitness",
        description: "The key components of a successful 21-day fitness routine would be to draft a doable plan, expect progressive success and realise that you don't have to stop living. Anything which fits well with your daily routine and time should be part of your 21-day routine. Be it exercise or diet. It is not a phase to go extreme but to go realistic with a lot of planning. How important is setting specific, achievable goals within a 21-day timeframe for someone looking to adopt a healthier lifestyle? The timeframe is not too long so it is important to set achievable goals. Don't expect big numbers on the scale. 3 weeks is a good way to adapt to a healthy lifestyle so think of it that way. It’s not enough to bring drastic changes but it is a great start to set a routine. Your routine needs to be sustainable. Try full-body workouts with strength training with 2-3kg dumbbells, kettlebells or resistance bands and focus on your shoulders, arms, chest, core, back, glutes, and legs. You can pick 2 exercises for each muscle group and stitch a routine around it. Walking to clock in 6,000 or 10,000 steps is a good way too. Moreover, cut off junk, alcohol, and sugar for healthier foods like vegetables, fruits and nuts.Often, people struggle with motivation when starting a new fitness routine. What advice do you have to keep individuals motivated and consistent throughout the 21 days? People struggle with motivation but you need to know that you just need to make a small goal and stick to it. Try to be in a circle of friends who are self-motivated or follow inspiring people. You can also start this challenge with your friends or loved ones to stay motivated. The biggest misconception is that something drastic will happen. Your body might respond differently and go through certain changes but don't set major expectations. Each body reacts differently to workouts and routine changes. What role does mental wellness play in achieving fitness goals within this 21-day timeframe, and how can individuals prioritise their mental health during this process? Wellness is holistic. It starts from what you're eating to what you’re thinking. Having a strong and positive mindset plays a huge role as well.How should individuals modify the routine to suit their needs and capabilities while staying true to the 21-day structure?"
      },
      {
        id: 32,
        Image: 'https://www.bing.com/th?id=OVFT.Fgj-naiZwTdXVI3BlYEtdC&pid=News&w=234&h=132&c=14&rs=2&qlt=90',
        heading:"17-YO Bodybuilder Leaves the Fitness World in Utter Disbelief: “Looks Absurd for 17” " ,
        category: "Fitness",
        description: "Body Building coach Brandon Clark has trained many young stars and always is training athletes to show their best. His program has benefitted many bodybuilders young and old and made them progress in their fitness. Each program contains different focal points and is designed to keep the person from plateauing all while increasing strength and overall physique.He recently uploaded a picture of his own pupil who is only 17 and benefitted from his training because he just achieved his first open OCB class bodybuilding prize. Fans were also astonished at the young man’s physique. Clark proudly posted the pictures of his trainee and wrote, “Big CONGRATS to my 17-year-old client @traviswright.06 for taking 2nd in his open OCB class Natural pro card is inevitable Also btw he did get drug tested… #naturalbodybuilding.” He is already becoming famous in TikTok and Instagram and he also uploads his practice and exercises on YouTube. Arnold Schwarzenegger had debuted at only 19 and this young man might surpass it since he is already participating in competitions at the young age of 17! "
      },
      {
        id: 33,
        Image: 'https://rareailessons.com/in-land/robotnoqueen.jpg',
        heading:" An app that uses artificial intelligence to make money has been released in India and is available to the public " ,
        category: "Technology",
        description: "Artificial intelligence technologies like ChatGPT and Midjourney are currently taking the world by storm. What most people don’t know though, is that AI technology isn’t new, in fact it’s been around for years. It wasn’t until recently, programmers have discovered that if the average person can use AI technology to make money on their behalf, removing human error, the potential for profit is huge – and that’s just what Bit GPT AI does automatically, even while you sleep. 3 biggest advantages of Bit GPT AI -By far, the biggest advantage of this application is because of artificial intelligence, there is minimal manual work required. It is currently only available in India, and the first users to register are already reporting earnings of at least $14,750 USD per month, well above the average for similar apps that have insane membership fees. Secondly, the app has a simple user interface, so no technical knowledge or experience is required to use it. The app comes with an algorithm that can independently determine which cryptocurrencies to buy and which to sell in order to maximize profits. Thirdly, withdrawals are fast (within 2 days of request) and reliable. Various payment methods are supported, such as cards, online accounts or bank transactions. To get started, you must deposit 20,000 Rupees or $250 in to your account balance so that the AI trading app can begin automatically buying and selling cryptocurrencies in order to generate profit. All transactions are carried out in a relatively short time, from a few minutes to several hours.The way the app determines which cryptocurrencies to buy and sell and at what time relies on the analysis of thousands of market indicators, from technical analysis of charts to world news that affect the movement of values. The real power of this app that sets it apart from others is an advanced AI algorithm that analyzes thousands of such signals every minute and is able to predict with extreme precision what to buy and sell at the right time to achieve maximum profit."
      },
      {
        id: 34,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lA3FS.img?w=549&h=309&m=6',
        heading:"Appy Pie Introduces Cutting-Edge No-Code AI App Development for Future-Ready Applications " ,
        category: "Technology",
        description: "Appy Pie, the leading no-code AI app development platform, stays true to its mission to revolutionize and democratize the tech industry with its pioneering advancements in AI-powered app development. Recognized as the biggest name in the field of no-code technology, Appy Pie announces a significant leap forward in simplifying AI app development for businesses and individuals alike making the technology accessible to all. With a persistent commitment to innovation and user-centric solutions, Appy Pie has harnessed the power of Artificial Intelligence (AI) to offer a seamless and intuitive app builder for creating complex apps without extensive coding knowledge. This groundbreaking approach ensures that anyone, regardless of technical expertise, can leverage AI capabilities to craft powerful and customized applications tailored to their specific needs. The integration of AI within the no-code platform allows users to effortlessly incorporate intelligent features such as predictive analytics, natural language processing, and machine learning algorithms into their applications. This transformative approach not only streamlines the development process but also opens new possibilities for businesses to create innovative solutions and enhance user experiences. Appy Pie's dedication to democratizing technology has garnered widespread acclaim, positioning the company as a frontrunner in the rapidly evolving landscape of app development. Through continuous innovation and a user-first approach, Appy Pie remains steadfast in its mission to empower individuals and businesses, enabling them to harness the full potential of AI-driven applications. Appy Pie, a Trademark of Appy Pie LLP, is a leading no-code development platform that helps transform business ideas into reality without requiring technical knowledge. It offers an all-inclusive suite of the best no-code tools, including an app builder, website builder, workflow automation platform, graphic design software, chatbot builder, help desk software, and live chat software. Appy Pie's App Maker has been recognized as one of the highest-rated app builders globally by G2, thanks to its unique features, ease of use, and affordability. It is considered one of the most comprehensive no-code application development software for businesses of all sizes according to Capterra. Moreover, Appy Pie is the fastest-growing cloud-based DIY Mobile App Builder in the world, as acknowledged by GetApp."
      },
      {
        id: 35,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lCTt1.img?w=768&h=432&m=6',
        heading:"The year ahead: Technology trends for 2024 " ,
        category: "Technology",
        description: "With the clock ticking away furiously towards the year 2024, one can gauge the pulse of technology as the year winds down.It is expected that Generative AI, Virtual reality, Sustainability, Quantum Computing, Autonomous Vehicles, Cybersecurity, and the Technology of Elections will take centrestage as we step into the future. Generative AI will take center stage as humans understand its potential for productivity, creativity, and insights as it catapults into applications- medicine, finance, marketing, and programming – the sky’s the limit. It’s an intelligent 24/7 co-pilot, at our beck and call to make us highly efficient. It can take over mundane tasks like scheduling, managing compliance, organising, and structuring tasks, and also creative ones like image and content generation. AI regulations and ethics are still being pondered- prime components of responsible AI. Left alone, humankind is at risk from unregulated AI.  Virtual Reality: Is it Real or Virtual?Virtual self, virtual reality, and immersive media are terms that are becoming mainstream. We use digital avatars that represent us online, speak to us, and interact with other virtual avatars. We are talking about a digital twin – a virtual representation of an object, system or process is built from data captured from the real-world counterpart. In 2024, the digital world will become more realistic and a part of our human world. Improvements in GPU technology and software will blur the virtual and the real world with textures, lighting, and environments to invoke human emotions."
      },
      {
        id: 36,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lDN3S.img?w=768&h=432&m=6',
        heading:" Generative AI can add $1.5 ​trillion to India's GDP by FY30: Report" ,
        category: "Technology",
        description: "New Delhi: Generative AI has the potential to add a cumulative $1.2-1.5 trillion to India's GDP over the next seven years, according to a report by Ernst & Young India.The report, titled 'The AIdea of India: Generative AI's potential to accelerate India's digital transformation', provided insights into the industry's preparedness and challenges in embracing Gen AI. Gen AI can potentially add a cumulative $1.2-1.5 trillion to India's GDP by FY29-30, as per the report. 'The report forecasts that by fully capitalising Gen AI technology and its applications across sectors, India can potentially add $359-438 billion in FY29-30 alone, reflecting a 5.9-7.2% increase over and above the baseline GDP,' it said.Nearly 69% of the overall impact is expected to be derived from sectors such as business services - including IT, legal, consulting, outsourcing, rental of machinery & equipment, and others - financial services, education, retail, and healthcare. The anticipated impact entails improvements in workforce productivity, increased operational efficiency, and personalised customer engagement, the report said. "
      },
      {
        id: 37,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lqYrc.img?w=600&h=338&m=6',
        heading:" Looking for ChatGPT alternatives? Check these top 5 replacements - Bard, Copilot, more" ,
        category: "Technology",
        description: "Ever since it was launched in November 2022, OpenAI's ChatGPT has created an artificial intelligence frenzy that is still going strong. ChatGPT is the pioneer when it comes to generative AI chatbot technology, and with its Generative Pre-Trained Transformer (GPT) foundational model, it can do pretty much anything a modern AI chatbot can. However, it is also one of the most general-purpose chatbots there is. If your use case requires you to go for something more nuanced or for a different capability, then these are the best ChatGPT alternatives that you should know about. The list includes Google Bard, Microsoft Copilot, and more.Best ChatGPT alternatives 1. Google Bard: Google Bard is based on the company's next-generation language and conversation capabilities powered by their Language Model for Dialogue Applications (LaMDA). Google Bard can generate a variety of responses, even from the same or similar prompts and questions. Once a user provides a prompt, Bard uses the context in the prompt and the interaction with the user to draft several versions of a response. The AI chatbot then classifies and checks its responses against predetermined safety parameters. If a user would like to see a different response or set of responses, they can ask Bard to generate a new response. Therefore, Google Bard should be used for creative collaborations, such as to generate a code for a program or give captions for photos. 2. Microsoft Copilot: Copilot, also known as Bing Chatbot, is a large language mode (LLM) chatbot developed by Microsoft. It is currently available in the Bing search engine and the Bing app. Like all chatbots, it can also answer most user queries and can generate text, draft emails, and more. It can also generate different creative text formats, like poems, code, scripts, musical pieces, letters, etc. Alongside, it can also help with unique tasks such as booking appointments, making travel arrangements, and shopping online.3. ChatSonic: ChatSonic is another conversational AI chatbot that takes advantage of the limitations of ChatGPT. Unlike OpenAI's generative AI model, ChatSonic can come up with up-to-date information with the ?Include Latest Google Data? option. Technologies such as GPT-4, Stable diffusion, DALL-E, Natural Language Processing (NLP), and Machine Learning (ML) are incorporated in ChatSonic which allows the AI chatbot to accept prompts and generate responses."
      },
      {
        id: 38,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lFcFr.img?w=509&h=286&m=6',
        heading:"Yes, your phone is listening: Study shows some advertisers are indeed eavesdropping " ,
        category: "Technology",
        description: "If you thought you were being paranoid about your phones listening to you, you can stop. Because you were probably right. Your phone is most likely listening to you, but the ears behind your phone are advertisers'. A review report by the Cox Media Group (CMG) reveals that the advertising company has the ability to tap into ambient conversations of users via built-in microphones in smartphones, smart TVs, and various gadgets to collect information and then employ that data for targeted advertising. As per the company, by 'Active Listening' advertisers like CMG get the information they need to pinpoint potential customers by analysing casual conversations in real-time. This was first reported by 404 Media.CMG has published a paper on its website on 'How Voice Data works and how you can use it in your business'. The introduction to the paper reads, 'What would it mean for your business if you could target potential clients who are actively discussing their need for your services in their day-to-day conversations? No, it's not a Black Mirror episode—it's Voice Data, and CMG has the capabilities to use it to your business advantage.'The paper further reads, 'That means a smart device is likely within earshot when we talk about our plans for the weekend, how badly we need our kitchen remodeled, or debate which SUV model is best…' Creepy? Sure. Great for marketing? Definitely,' the paper further reads. Yes, this is exactly what you are thinking about, because I am sure this has happened to you at least once before. A lot of times you are having a conversation (not on the phone) with a friend, say about buying a toaster, and minutes later when you pick up your phone and start surfing through social media, you start to see ads for toasters. This is when you have never actually searched for the said toaster before on your phone. All you have had is that conversation with your friend, and now you are seeing hoards of advertisements for it on different social media apps.   "
      },
      {
        id: 39,
        Image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1lAWsp.img?w=768&h=512&m=6',
        heading:"Recalling almost every Tesla in America won’t fix safety issues, experts say " ,
        category: "Technology",
        description: "Tesla this week agreed to issue a remote update to 2 million cars aimed at improving driver attention while Autopilot is engaged, especially on surface roads with cross traffic and other hazards the driver-assistance technology is not designed to detect.But the recall — the largest in Tesla’s 20-year history — quickly drew condemnation from experts and lawmakers, who said new warnings and alerts are unlikely to solve Autopilot’s fundamental flaw: that Tesla fails to limit where drivers can turn it on in the first place.“What a missed opportunity,” said Matthew Wansley, a professor at the Cardozo School of Law in New York who specializes in emerging automotive technologies. “I have yet to see Tesla, or anyone defending Tesla, come up with an argument for why we should be letting people use [Autopilot] on roads that could have cross traffic. That’s how a lot of these crashes are happening.” “It’s far from sufficient,” added Sen. Richard Blumenthal (D-Conn.), a frequent Tesla critic.How Tesla's Autopilot got groundedThe recall comes more than two years after the National Highway Traffic Safety Administration (NHTSA) first launched an investigation into Autopilot after a string of Teslas plowed into parked emergency vehicles. Since then, the agency said it had reviewed more than 900 crashes involving Autopilot. It found that Autopilot’s key Autosteer feature “may not” have sufficient controls to “prevent driver misuse,” including using the feature outside the controlled-access highways for which it was designed.The notice said Tesla did not concur with the agency’s findings, though it began sending remote software updates on Tuesday, NHTSA said. "
      },
      {
        id: 40,
        Image: 'https://imageio.forbes.com/specials-images/imageserve/657b12721b35444dbbfe6abe/African-engineer-with-tablet-inspection-the-Robotic-arm-and-working-at-manufacturing/960x0.jpg?format=jpg&width=1440',
        heading:"Technology Vs. Humans: Finding A Balance " ,
        category: "Technology",
        description: "Labor disputes have been in the news. Strikes in the U.S. automotive and entertainment industries have served as reminders of tension not only between workers and management but also between humans and technology. This is not a new scenario. Automated assembly lines and robotics have long had a labor displacement effect. Up ahead for the automotive industry lies even more efficient production, with electric vehicles possibly requiring 30% to 40% less human labor. As for the entertainment business, new distribution technologies that have emerged over several decades have led content creators to seek expanded rights. What’s new is how technologies like artificial intelligence and its powerful machine learning subset are beginning to transform businesses further. Being the CEO of a company that provides AI and automation solutions, I'm finding that technology-worker tensions are appearing at the start of the value chain with content creation and design, as well as on the edge, where users or customers interact with products and services.Workers Vs. AI - Beyond the more familiar fights related to money and distribution, earlier this year, striking Hollywood writers were also concerned about AI. The Alliance of Motion Picture and Television Producers ultimately 'agreed to language protecting writers from the use of AI in the writing process, giving them credit for their work and allowing writers to determine if their writing can be used to train AI,' according to NPR."
      },

    ])
    return(
     <Store.Provider value = {[data, setData]}>
        {props.children}
     </Store.Provider>
    
    )
  
  
}

export default DataComp